require "net/http"
require "json"
require "kconv"
require 'erb'
require "mechanize"
require "romaji"
require "nkf"

module Mobamasu

CHARACTER_LIST = [
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 11,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "相川",
		"family_name_ruby" => "あいかわ",
		"first_name" => "千夏",
		"first_name_ruby" => "ちなつ",
		"gender" => 2,
		"id" => 71,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "相川千夏",
		"name_ruby" => "あいかわちなつ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 1,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "愛野",
		"family_name_ruby" => "あいの",
		"first_name" => "渚",
		"first_name_ruby" => "なぎさ",
		"gender" => 2,
		"id" => 105,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "愛野渚",
		"name_ruby" => "あいのなぎさ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 14,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "相原",
		"family_name_ruby" => "あいはら",
		"first_name" => "雪乃",
		"first_name_ruby" => "ゆきの",
		"gender" => 2,
		"id" => 53,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "相原雪乃",
		"name_ruby" => "あいはらゆきの",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 15,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "相葉",
		"family_name_ruby" => "あいば",
		"first_name" => "夕美",
		"first_name_ruby" => "ゆみ",
		"gender" => 2,
		"id" => 109,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "相葉夕美",
		"name_ruby" => "あいばゆみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 14,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "黒沢ともよ",
		"family_name" => "赤城",
		"family_name_ruby" => "あかぎ",
		"first_name" => "みりあ",
		"first_name_ruby" => "みりあ",
		"gender" => 2,
		"id" => 104,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "赤城みりあ",
		"name_ruby" => "あかぎみりあ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 7,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "赤西",
		"family_name_ruby" => "あかにし",
		"first_name" => "瑛梨華",
		"first_name_ruby" => "えりか",
		"gender" => 2,
		"id" => 51,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "赤西瑛梨華",
		"name_ruby" => "あかにしえりか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-31",
		"birth_day" => 11,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "浅野",
		"family_name_ruby" => "あさの",
		"first_name" => "風香",
		"first_name_ruby" => "ふうか",
		"gender" => 2,
		"id" => 155,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "浅野風香",
		"name_ruby" => "あさのふうか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2014-02-19",
		"birth_day" => 9,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "浅利",
		"family_name_ruby" => "あさり",
		"first_name" => "七海",
		"first_name_ruby" => "ななみ",
		"gender" => 2,
		"id" => 269,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "浅利七海",
		"name_ruby" => "あさりななみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-01-18",
		"birth_day" => 19,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "上坂すみれ",
		"family_name" => "",
		"family_name_ruby" => "",
		"first_name" => "アナスタシア",
		"first_name_ruby" => "あなすたしあ",
		"gender" => 2,
		"id" => 214,
		"is_foreigner_name" => true,
		"is_idol" => true,
		"name" => "アナスタシア",
		"name_ruby" => "あなすたしあ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-02-22",
		"birth_day" => 15,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "三宅麻理恵",
		"family_name" => "安部",
		"family_name_ruby" => "あべ",
		"first_name" => "菜々",
		"first_name_ruby" => "なな",
		"gender" => 2,
		"id" => 161,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "安部菜々",
		"name_ruby" => "あべなな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 29,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "綾瀬",
		"family_name_ruby" => "あやせ",
		"first_name" => "穂乃香",
		"first_name_ruby" => "ほのか",
		"gender" => 2,
		"id" => 91,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "綾瀬穂乃香",
		"name_ruby" => "あやせほのか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 9,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "荒木",
		"family_name_ruby" => "あらき",
		"first_name" => "比奈",
		"first_name_ruby" => "ひな",
		"gender" => 2,
		"id" => 75,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "荒木比奈",
		"name_ruby" => "あらきひな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-09-11",
		"birth_day" => 6,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "有浦",
		"family_name_ruby" => "ありうら",
		"first_name" => "柑奈",
		"first_name_ruby" => "かんな",
		"gender" => 2,
		"id" => 265,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "有浦柑奈",
		"name_ruby" => "ありうらかんな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-23",
		"birth_day" => 6,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "安斎",
		"family_name_ruby" => "あんざい",
		"first_name" => "都",
		"first_name_ruby" => "みやこ",
		"gender" => 2,
		"id" => 152,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "安斎都",
		"name_ruby" => "あんざいみやこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 10,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "五十嵐",
		"family_name_ruby" => "いがらし",
		"first_name" => "響子",
		"first_name_ruby" => "きょうこ",
		"gender" => 2,
		"id" => 48,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "五十嵐響子",
		"name_ruby" => "いがらしきょうこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-28",
		"birth_day" => 10,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "池袋",
		"family_name_ruby" => "いけぶくろ",
		"first_name" => "晶葉",
		"first_name_ruby" => "あきは",
		"gender" => 2,
		"id" => 138,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "池袋晶葉",
		"name_ruby" => "いけぶくろあきは",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 24,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "伊集院",
		"family_name_ruby" => "いじゅういん",
		"first_name" => "惠",
		"first_name_ruby" => "めぐみ",
		"gender" => 2,
		"id" => 86,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "伊集院惠",
		"name_ruby" => "いじゅういんめぐみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2014-02-19",
		"birth_day" => 30,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "一ノ瀬",
		"family_name_ruby" => "いちのせ",
		"first_name" => "志希",
		"first_name_ruby" => "しき",
		"gender" => 2,
		"id" => 270,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "一ノ瀬志希",
		"name_ruby" => "いちのせしき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-28",
		"birth_day" => 8,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "久野美咲",
		"family_name" => "市原",
		"family_name_ruby" => "いちはら",
		"first_name" => "仁奈",
		"first_name_ruby" => "にな",
		"gender" => 2,
		"id" => 137,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "市原仁奈",
		"name_ruby" => "いちはらにな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-09",
		"birth_day" => 24,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "サンタクロース",
		"family_name_ruby" => "さんたくろーす",
		"first_name" => "イヴ",
		"first_name_ruby" => "いぶ",
		"gender" => 2,
		"id" => 133,
		"is_foreigner_name" => true,
		"is_idol" => true,
		"name" => "イヴ・サンタクロース",
		"name_ruby" => "いぶさんたくろーす",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 3,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "今井",
		"family_name_ruby" => "いまい",
		"first_name" => "加奈",
		"first_name_ruby" => "かな",
		"gender" => 2,
		"id" => 41,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "今井加奈",
		"name_ruby" => "いまいかな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-09",
		"birth_day" => 27,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "井村",
		"family_name_ruby" => "いむら",
		"first_name" => "雪菜",
		"first_name_ruby" => "せつな",
		"gender" => 2,
		"id" => 131,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "井村雪菜",
		"name_ruby" => "いむらせつな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-28",
		"birth_day" => 26,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "上田",
		"family_name_ruby" => "うえだ",
		"first_name" => "鈴帆",
		"first_name_ruby" => "すずほ",
		"gender" => 2,
		"id" => 136,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "上田鈴帆",
		"name_ruby" => "うえだすずほ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-31",
		"birth_day" => 13,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "氏家",
		"family_name_ruby" => "うじいえ",
		"first_name" => "むつみ",
		"first_name_ruby" => "むつみ",
		"gender" => 2,
		"id" => 157,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "氏家むつみ",
		"name_ruby" => "うじいえむつみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-13",
		"birth_day" => 20,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "梅木",
		"family_name_ruby" => "うめき",
		"first_name" => "音葉",
		"first_name_ruby" => "おとは",
		"gender" => 2,
		"id" => 150,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "梅木音葉",
		"name_ruby" => "うめきおとは",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-28",
		"birth_day" => 6,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "江上",
		"family_name_ruby" => "えがみ",
		"first_name" => "椿",
		"first_name_ruby" => "つばき",
		"gender" => 2,
		"id" => 134,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "江上椿",
		"name_ruby" => "えがみつばき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-06-26",
		"birth_day" => 18,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "衛藤",
		"family_name_ruby" => "えとう",
		"first_name" => "美紗希",
		"first_name_ruby" => "みさき",
		"gender" => 2,
		"id" => 183,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "衛藤美紗希",
		"name_ruby" => "えとうみさき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-13",
		"birth_day" => 3,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "海老原",
		"family_name_ruby" => "えびはら",
		"first_name" => "菜帆",
		"first_name_ruby" => "なほ",
		"gender" => 2,
		"id" => 148,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "海老原菜帆",
		"name_ruby" => "えびはらなほ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-04-13",
		"birth_day" => 3,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "及川",
		"family_name_ruby" => "おいかわ",
		"first_name" => "雫",
		"first_name_ruby" => "しずく",
		"gender" => 2,
		"id" => 173,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "及川雫",
		"name_ruby" => "おいかわしずく",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-08-14",
		"birth_day" => 11,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "大石",
		"family_name_ruby" => "おおいし",
		"first_name" => "泉",
		"first_name_ruby" => "いずみ",
		"gender" => 2,
		"id" => 188,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "大石泉",
		"name_ruby" => "おおいしいずみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-09-18",
		"birth_day" => 28,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "太田",
		"family_name_ruby" => "おおた",
		"first_name" => "優",
		"first_name_ruby" => "ゆう",
		"gender" => 2,
		"id" => 190,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "太田優",
		"name_ruby" => "おおたゆう",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 7,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "大槻",
		"family_name_ruby" => "おおつき",
		"first_name" => "唯",
		"first_name_ruby" => "ゆい",
		"gender" => 2,
		"id" => 107,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "大槻唯",
		"name_ruby" => "おおつきゆい",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-31",
		"birth_day" => 20,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "大西",
		"family_name_ruby" => "おおにし",
		"first_name" => "由里子",
		"first_name_ruby" => "ゆりこ",
		"gender" => 2,
		"id" => 156,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "大西由里子",
		"name_ruby" => "おおにしゆりこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-12-19",
		"birth_day" => 30,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "大沼",
		"family_name_ruby" => "おおぬま",
		"first_name" => "くるみ",
		"first_name_ruby" => "くるみ",
		"gender" => 2,
		"id" => 266,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "大沼くるみ",
		"name_ruby" => "おおぬまくるみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-05-21",
		"birth_day" => 12,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "大原",
		"family_name_ruby" => "おおはら",
		"first_name" => "みちる",
		"first_name_ruby" => "みちる",
		"gender" => 2,
		"id" => 258,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "大原みちる",
		"name_ruby" => "おおはらみちる",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-05-14",
		"birth_day" => 16,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "岡崎",
		"family_name_ruby" => "おかざき",
		"first_name" => "泰葉",
		"first_name_ruby" => "やすは",
		"gender" => 2,
		"id" => 181,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "岡崎泰葉",
		"name_ruby" => "おかざきやすは",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 11,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "大空直美",
		"family_name" => "緒方",
		"family_name_ruby" => "おがた",
		"first_name" => "智絵里",
		"first_name_ruby" => "ちえり",
		"gender" => 2,
		"id" => 47,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "緒方智絵里",
		"name_ruby" => "おがたちえり",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 12,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "奥山",
		"family_name_ruby" => "おくやま",
		"first_name" => "沙織",
		"first_name_ruby" => "さおり",
		"gender" => 2,
		"id" => 44,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "奥山沙織",
		"name_ruby" => "おくやまさおり",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2014-05-28",
		"birth_day" => 6,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "乙倉",
		"family_name_ruby" => "おとくら",
		"first_name" => "悠貴",
		"first_name_ruby" => "ゆうき",
		"gender" => 2,
		"id" => 274,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "乙倉悠貴",
		"name_ruby" => "おとくらゆうき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-11-06",
		"birth_day" => 7,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "片桐",
		"family_name_ruby" => "かたぎり",
		"first_name" => "早苗",
		"first_name_ruby" => "さなえ",
		"gender" => 2,
		"id" => 209,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "片桐早苗",
		"name_ruby" => "かたぎりさなえ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 10,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "上条",
		"family_name_ruby" => "かみじょう",
		"first_name" => "春菜",
		"first_name_ruby" => "はるな",
		"gender" => 2,
		"id" => 74,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "上条春菜",
		"name_ruby" => "かみじょうはるな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 16,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "松井恵理子",
		"family_name" => "神谷",
		"family_name_ruby" => "かみや",
		"first_name" => "奈緒",
		"first_name_ruby" => "なお",
		"gender" => 2,
		"id" => 73,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "神谷奈緒",
		"name_ruby" => "かみやなお",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 25,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "東山奈央",
		"family_name" => "川島",
		"family_name_ruby" => "かわしま",
		"first_name" => "瑞樹",
		"first_name_ruby" => "みずき",
		"gender" => 2,
		"id" => 72,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "川島瑞樹",
		"name_ruby" => "かわしまみずき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 8,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "内田真礼",
		"family_name" => "神崎",
		"family_name_ruby" => "かんざき",
		"first_name" => "蘭子",
		"first_name_ruby" => "らんこ",
		"gender" => 2,
		"id" => 85,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "神崎蘭子",
		"name_ruby" => "かんざきらんこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-23",
		"birth_day" => 13,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "岸部",
		"family_name_ruby" => "きしべ",
		"first_name" => "彩華",
		"first_name_ruby" => "あやか",
		"gender" => 2,
		"id" => 153,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "岸部彩華",
		"name_ruby" => "きしべあやか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-23",
		"birth_day" => 17,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "北川",
		"family_name_ruby" => "きたがわ",
		"first_name" => "真尋",
		"first_name_ruby" => "まひろ",
		"gender" => 2,
		"id" => 154,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "北川真尋",
		"name_ruby" => "きたがわまひろ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-31",
		"birth_day" => 6,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "喜多",
		"family_name_ruby" => "きた",
		"first_name" => "日菜子",
		"first_name_ruby" => "ひなこ",
		"gender" => 2,
		"id" => 145,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "喜多日菜子",
		"name_ruby" => "きたひなこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-09",
		"birth_day" => 2,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "喜多見",
		"family_name_ruby" => "きたみ",
		"first_name" => "柚",
		"first_name_ruby" => "ゆず",
		"gender" => 2,
		"id" => 130,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "喜多見柚",
		"name_ruby" => "きたみゆず",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-13",
		"birth_day" => 8,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "木場",
		"family_name_ruby" => "きば",
		"first_name" => "真奈美",
		"first_name_ruby" => "まなみ",
		"gender" => 2,
		"id" => 147,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "木場真奈美",
		"name_ruby" => "きばまなみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 19,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "木村",
		"family_name_ruby" => "きむら",
		"first_name" => "夏樹",
		"first_name_ruby" => "なつき",
		"gender" => 2,
		"id" => 99,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "木村夏樹",
		"name_ruby" => "きむらなつき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-02-29",
		"birth_day" => 19,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "グラハム",
		"family_name_ruby" => "ぐらはむ",
		"first_name" => "キャシー",
		"first_name_ruby" => "きゃしー",
		"gender" => 2,
		"id" => 166,
		"is_foreigner_name" => true,
		"is_idol" => true,
		"name" => "キャシー・グラハム",
		"name_ruby" => "きゃしーぐらはむ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 8,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "桐野",
		"family_name_ruby" => "きりの",
		"first_name" => "アヤ",
		"first_name_ruby" => "あや",
		"gender" => 2,
		"id" => 69,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "桐野アヤ",
		"name_ruby" => "きりのあや",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2014-09-19",
		"birth_day" => 24,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "桐生",
		"family_name_ruby" => "きりゅう",
		"first_name" => "つかさ",
		"first_name_ruby" => "つかさ",
		"gender" => 2,
		"id" => 314,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "桐生つかさ",
		"name_ruby" => "きりゅうつかさ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-31",
		"birth_day" => 4,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "日下部",
		"family_name_ruby" => "くさかべ",
		"first_name" => "若葉",
		"first_name_ruby" => "わかば",
		"gender" => 2,
		"id" => 140,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "日下部若葉",
		"name_ruby" => "くさかべわかば",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-02-29",
		"birth_day" => 9,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "工藤",
		"family_name_ruby" => "くどう",
		"first_name" => "忍",
		"first_name_ruby" => "しのぶ",
		"gender" => 2,
		"id" => 162,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "工藤忍",
		"name_ruby" => "くどうしのぶ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-05-14",
		"birth_day" => 26,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "",
		"family_name_ruby" => "",
		"first_name" => "クラリス",
		"first_name_ruby" => "くらりす",
		"gender" => 2,
		"id" => 180,
		"is_foreigner_name" => true,
		"is_idol" => true,
		"name" => "クラリス",
		"name_ruby" => "くらりす",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-02-29",
		"birth_day" => 9,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "栗原",
		"family_name_ruby" => "くりはら",
		"first_name" => "ネネ",
		"first_name_ruby" => "ねね",
		"gender" => 2,
		"id" => 163,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "栗原ネネ",
		"name_ruby" => "くりはらねね",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 26,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "黒川",
		"family_name_ruby" => "くろかわ",
		"first_name" => "千秋",
		"first_name_ruby" => "ちあき",
		"gender" => 2,
		"id" => 67,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "黒川千秋",
		"name_ruby" => "くろかわちあき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 15,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "",
		"family_name_ruby" => "",
		"first_name" => "ケイト",
		"first_name_ruby" => "けいと",
		"gender" => 2,
		"id" => 89,
		"is_foreigner_name" => true,
		"is_idol" => true,
		"name" => "ケイト",
		"name_ruby" => "けいと",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-03-15",
		"birth_day" => 1,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "古賀",
		"family_name_ruby" => "こが",
		"first_name" => "小春",
		"first_name_ruby" => "こはる",
		"gender" => 2,
		"id" => 171,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "古賀小春",
		"name_ruby" => "こがこはる",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-13",
		"birth_day" => 25,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "竹達彩奈",
		"family_name" => "輿水",
		"family_name_ruby" => "こしみず",
		"first_name" => "幸子",
		"first_name_ruby" => "さちこ",
		"gender" => 2,
		"id" => 149,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "輿水幸子",
		"name_ruby" => "こしみずさちこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-05-14",
		"birth_day" => 5,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "小関",
		"family_name_ruby" => "こせき",
		"first_name" => "麗奈",
		"first_name_ruby" => "れいな",
		"gender" => 2,
		"id" => 179,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "小関麗奈",
		"name_ruby" => "こせきれいな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 18,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "立花理香",
		"family_name" => "小早川",
		"family_name_ruby" => "こばやかわ",
		"first_name" => "紗枝",
		"first_name_ruby" => "さえ",
		"gender" => 2,
		"id" => 55,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "小早川紗枝",
		"name_ruby" => "こばやかわさえ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 16,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "津田美波",
		"family_name" => "小日向",
		"family_name_ruby" => "こひなた",
		"first_name" => "美穂",
		"first_name_ruby" => "みほ",
		"gender" => 2,
		"id" => 46,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "小日向美穂",
		"name_ruby" => "こひなたみほ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-31",
		"birth_day" => 17,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "小松",
		"family_name_ruby" => "こまつ",
		"first_name" => "伊吹",
		"first_name_ruby" => "いぶき",
		"gender" => 2,
		"id" => 160,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "小松伊吹",
		"name_ruby" => "こまついぶき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 9,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "小室",
		"family_name_ruby" => "こむろ",
		"first_name" => "千奈美",
		"first_name_ruby" => "ちなみ",
		"gender" => 2,
		"id" => 82,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "小室千奈美",
		"name_ruby" => "こむろちなみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 23,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "西園寺",
		"family_name_ruby" => "さいおんじ",
		"first_name" => "琴歌",
		"first_name_ruby" => "ことか",
		"gender" => 2,
		"id" => 56,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "西園寺琴歌",
		"name_ruby" => "さいおんじことか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 29,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "斉藤",
		"family_name_ruby" => "さいとう",
		"first_name" => "洋子",
		"first_name_ruby" => "ようこ",
		"gender" => 2,
		"id" => 101,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "斉藤洋子",
		"name_ruby" => "さいとうようこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-07-17",
		"birth_day" => 26,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "冴島",
		"family_name_ruby" => "さえじま",
		"first_name" => "清美",
		"first_name_ruby" => "きよみ",
		"gender" => 2,
		"id" => 262,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "冴島清美",
		"name_ruby" => "さえじまきよみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-31",
		"birth_day" => 27,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "榊原",
		"family_name_ruby" => "さかきばら",
		"first_name" => "里美",
		"first_name_ruby" => "さとみ",
		"gender" => 2,
		"id" => 141,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "榊原里美",
		"name_ruby" => "さかきばらさとみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-05-21",
		"birth_day" => 27,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "M・A・O",
		"family_name" => "鷺沢",
		"family_name_ruby" => "さぎさわ",
		"first_name" => "文香",
		"first_name_ruby" => "ふみか",
		"gender" => 2,
		"id" => 257,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "鷺沢文香",
		"name_ruby" => "さぎさわふみか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-06-26",
		"birth_day" => 7,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "牧野由依",
		"family_name" => "佐久間",
		"family_name_ruby" => "さくま",
		"first_name" => "まゆ",
		"first_name_ruby" => "まゆ",
		"gender" => 2,
		"id" => 185,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "佐久間まゆ",
		"name_ruby" => "さくままゆ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-09",
		"birth_day" => 8,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "櫻井",
		"family_name_ruby" => "さくらい",
		"first_name" => "桃華",
		"first_name_ruby" => "ももか",
		"gender" => 2,
		"id" => 128,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "櫻井桃華",
		"name_ruby" => "さくらいももか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 7,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "佐々木",
		"family_name_ruby" => "ささき",
		"first_name" => "千枝",
		"first_name_ruby" => "ちえ",
		"gender" => 2,
		"id" => 79,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "佐々木千枝",
		"name_ruby" => "ささきちえ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 28,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "佐城",
		"family_name_ruby" => "さじょう",
		"first_name" => "雪美",
		"first_name_ruby" => "ゆきみ",
		"gender" => 2,
		"id" => 92,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "佐城雪美",
		"name_ruby" => "さじょうゆきみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2014-02-19",
		"birth_day" => 22,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "佐藤",
		"family_name_ruby" => "さとう",
		"first_name" => "心",
		"first_name_ruby" => "しん",
		"gender" => 2,
		"id" => 271,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "佐藤心",
		"name_ruby" => "さとうしん",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 6,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "沢田",
		"family_name_ruby" => "さわだ",
		"first_name" => "麻理菜",
		"first_name_ruby" => "まりな",
		"gender" => 2,
		"id" => 102,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "沢田麻理菜",
		"name_ruby" => "さわだまりな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-12-19",
		"birth_day" => 18,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "財前",
		"family_name_ruby" => "ざいぜん",
		"first_name" => "時子",
		"first_name_ruby" => "ときこ",
		"gender" => 2,
		"id" => 267,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "財前時子",
		"name_ruby" => "ざいぜんときこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 10,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "椎名",
		"family_name_ruby" => "しいな",
		"first_name" => "法子",
		"first_name_ruby" => "のりこ",
		"gender" => 2,
		"id" => 40,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "椎名法子",
		"name_ruby" => "しいなのりこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-04-13",
		"birth_day" => 12,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "塩見",
		"family_name_ruby" => "しおみ",
		"first_name" => "周子",
		"first_name_ruby" => "しゅうこ",
		"gender" => 2,
		"id" => 174,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "塩見周子",
		"name_ruby" => "しおみしゅうこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 22,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "篠原",
		"family_name_ruby" => "しのはら",
		"first_name" => "礼",
		"first_name_ruby" => "れい",
		"gender" => 2,
		"id" => 93,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "篠原礼",
		"name_ruby" => "しのはられい",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 10,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "福原綾香",
		"family_name" => "渋谷",
		"family_name_ruby" => "しぶや",
		"first_name" => "凛",
		"first_name_ruby" => "りん",
		"gender" => 2,
		"id" => 66,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "渋谷凛",
		"name_ruby" => "しぶやりん",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 24,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "大橋彩香",
		"family_name" => "島村",
		"family_name_ruby" => "しまむら",
		"first_name" => "卯月",
		"first_name_ruby" => "うづき",
		"gender" => 2,
		"id" => 36,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "島村卯月",
		"name_ruby" => "しまむらうづき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-09-18",
		"birth_day" => 18,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "首藤",
		"family_name_ruby" => "しゅとう",
		"first_name" => "葵",
		"first_name_ruby" => "あおい",
		"gender" => 2,
		"id" => 193,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "首藤葵",
		"name_ruby" => "しゅとうあおい",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-01-18",
		"birth_day" => 19,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "白菊",
		"family_name_ruby" => "しらぎく",
		"first_name" => "ほたる",
		"first_name_ruby" => "ほたる",
		"gender" => 2,
		"id" => 215,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "白菊ほたる",
		"name_ruby" => "しらぎくほたる",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-12",
		"birth_day" => 28,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "桜咲千依",
		"family_name" => "白坂",
		"family_name_ruby" => "しらさか",
		"first_name" => "小梅",
		"first_name_ruby" => "こうめ",
		"gender" => 2,
		"id" => 151,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "白坂小梅",
		"name_ruby" => "しらさかこうめ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 12,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "佳村はるか",
		"family_name" => "城ヶ崎",
		"family_name_ruby" => "じょうがさき",
		"first_name" => "美嘉",
		"first_name_ruby" => "みか",
		"gender" => 2,
		"id" => 113,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "城ヶ崎美嘉",
		"name_ruby" => "じょうがさきみか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 30,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "山本希望",
		"family_name" => "城ヶ崎",
		"family_name_ruby" => "じょうがさき",
		"first_name" => "莉嘉",
		"first_name_ruby" => "りか",
		"gender" => 2,
		"id" => 114,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "城ヶ崎莉嘉",
		"name_ruby" => "じょうがさきりか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-31",
		"birth_day" => 20,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "杉坂",
		"family_name_ruby" => "すぎさか",
		"first_name" => "海",
		"first_name_ruby" => "うみ",
		"gender" => 2,
		"id" => 144,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "杉坂海",
		"name_ruby" => "すぎさかうみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 28,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "涼宮",
		"family_name_ruby" => "すずみや",
		"first_name" => "星花",
		"first_name_ruby" => "せいか",
		"gender" => 2,
		"id" => 60,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "涼宮星花",
		"name_ruby" => "すずみやせいか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-04-13",
		"birth_day" => 17,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "関",
		"family_name_ruby" => "せき",
		"first_name" => "裕美",
		"first_name_ruby" => "ひろみ",
		"gender" => 2,
		"id" => 172,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "関裕美",
		"name_ruby" => "せきひろみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 10,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "瀬名",
		"family_name_ruby" => "せな",
		"first_name" => "詩織",
		"first_name_ruby" => "しおり",
		"gender" => 2,
		"id" => 90,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "瀬名詩織",
		"name_ruby" => "せなしおり",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 28,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "",
		"cv" => "佐藤利奈",
		"family_name" => "千川",
		"family_name_ruby" => "せんかわ",
		"first_name" => "ちひろ",
		"first_name_ruby" => "ちひろ",
		"gender" => 2,
		"id" => 127,
		"is_foreigner_name" => false,
		"is_idol" => false,
		"name" => "千川ちひろ",
		"name_ruby" => "せんかわちひろ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 27,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "仙崎",
		"family_name_ruby" => "せんざき",
		"first_name" => "恵磨",
		"first_name_ruby" => "えま",
		"gender" => 2,
		"id" => 115,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "仙崎恵磨",
		"name_ruby" => "せんざきえま",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 23,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "相馬",
		"family_name_ruby" => "そうま",
		"first_name" => "夏美",
		"first_name_ruby" => "なつみ",
		"gender" => 2,
		"id" => 120,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "相馬夏美",
		"name_ruby" => "そうまなつみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 14,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "早見沙織",
		"family_name" => "高垣",
		"family_name_ruby" => "たかがき",
		"first_name" => "楓",
		"first_name_ruby" => "かえで",
		"gender" => 2,
		"id" => 84,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "高垣楓",
		"name_ruby" => "たかがきかえで",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 8,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "高橋",
		"family_name_ruby" => "たかはし",
		"first_name" => "礼子",
		"first_name_ruby" => "れいこ",
		"gender" => 2,
		"id" => 70,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "高橋礼子",
		"name_ruby" => "たかはしれいこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-28",
		"birth_day" => 1,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "鷹富士",
		"family_name_ruby" => "たかふじ",
		"first_name" => "茄子",
		"first_name_ruby" => "かこ",
		"gender" => 2,
		"id" => 139,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "鷹富士茄子",
		"name_ruby" => "たかふじかこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 25,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "高峯",
		"family_name_ruby" => "たかみね",
		"first_name" => "のあ",
		"first_name_ruby" => "のあ",
		"gender" => 2,
		"id" => 83,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "高峯のあ",
		"name_ruby" => "たかみねのあ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 25,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "金子有希",
		"family_name" => "高森",
		"family_name_ruby" => "たかもり",
		"first_name" => "藍子",
		"first_name_ruby" => "あいこ",
		"gender" => 2,
		"id" => 96,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "高森藍子",
		"name_ruby" => "たかもりあいこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 30,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "青木瑠璃子",
		"family_name" => "多田",
		"family_name_ruby" => "ただ",
		"first_name" => "李衣菜",
		"first_name_ruby" => "りいな",
		"gender" => 2,
		"id" => 77,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "多田李衣菜",
		"name_ruby" => "ただりいな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-11-06",
		"birth_day" => 31,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "佐藤亜美菜",
		"family_name" => "橘",
		"family_name_ruby" => "たちばな",
		"first_name" => "ありす",
		"first_name_ruby" => "ありす",
		"gender" => 2,
		"id" => 208,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "橘ありす",
		"name_ruby" => "たちばなありす",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 30,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "月宮",
		"family_name_ruby" => "つきみや",
		"first_name" => "雅",
		"first_name_ruby" => "みやび",
		"gender" => 2,
		"id" => 61,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "月宮雅",
		"name_ruby" => "つきみやみやび",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-08-14",
		"birth_day" => 2,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "土屋",
		"family_name_ruby" => "つちや",
		"first_name" => "亜子",
		"first_name_ruby" => "あこ",
		"gender" => 2,
		"id" => 189,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "土屋亜子",
		"name_ruby" => "つちやあこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 7,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "東郷",
		"family_name_ruby" => "とうごう",
		"first_name" => "あい",
		"first_name_ruby" => "あい",
		"gender" => 2,
		"id" => 76,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "東郷あい",
		"name_ruby" => "とうごうあい",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 8,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "原田ひとみ",
		"family_name" => "十時",
		"family_name_ruby" => "ととき",
		"first_name" => "愛梨",
		"first_name_ruby" => "あいり",
		"gender" => 2,
		"id" => 118,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "十時愛梨",
		"name_ruby" => "とときあいり",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 10,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "",
		"family_name_ruby" => "",
		"first_name" => "トレーナー",
		"first_name_ruby" => "とれーなー",
		"gender" => 2,
		"id" => 124,
		"is_foreigner_name" => true,
		"is_idol" => false,
		"name" => "トレーナー",
		"name_ruby" => "とれーなー",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 1,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "道明寺",
		"family_name_ruby" => "どうみょうじ",
		"first_name" => "歌鈴",
		"first_name_ruby" => "かりん",
		"gender" => 2,
		"id" => 63,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "道明寺歌鈴",
		"name_ruby" => "どうみょうじかりん",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 23,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "中野",
		"family_name_ruby" => "なかの",
		"first_name" => "有香",
		"first_name_ruby" => "ゆか",
		"gender" => 2,
		"id" => 37,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "中野有香",
		"name_ruby" => "なかのゆか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-13",
		"birth_day" => 19,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "長富",
		"family_name_ruby" => "ながとみ",
		"first_name" => "蓮実",
		"first_name_ruby" => "はすみ",
		"gender" => 2,
		"id" => 146,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "長富蓮実",
		"name_ruby" => "ながとみはすみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 29,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "",
		"family_name_ruby" => "",
		"first_name" => "ナターリア",
		"first_name_ruby" => "なたーりあ",
		"gender" => 2,
		"id" => 119,
		"is_foreigner_name" => true,
		"is_idol" => true,
		"name" => "ナターリア",
		"name_ruby" => "なたーりあ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 14,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "並木",
		"family_name_ruby" => "なみき",
		"first_name" => "芽衣子",
		"first_name_ruby" => "めいこ",
		"gender" => 2,
		"id" => 97,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "並木芽衣子",
		"name_ruby" => "なみきめいこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-02-29",
		"birth_day" => 3,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "成宮",
		"family_name_ruby" => "なるみや",
		"first_name" => "由愛",
		"first_name_ruby" => "ゆめ",
		"gender" => 2,
		"id" => 164,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "成宮由愛",
		"name_ruby" => "なるみやゆめ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 13,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "南条",
		"family_name_ruby" => "なんじょう",
		"first_name" => "光",
		"first_name_ruby" => "ひかる",
		"gender" => 2,
		"id" => 123,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "南条光",
		"name_ruby" => "なんじょうひかる",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-03-15",
		"birth_day" => 1,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "難波",
		"family_name_ruby" => "なんば",
		"first_name" => "笑美",
		"first_name_ruby" => "えみ",
		"gender" => 2,
		"id" => 170,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "難波笑美",
		"name_ruby" => "なんばえみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-31",
		"birth_day" => 23,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "西川",
		"family_name_ruby" => "にしかわ",
		"first_name" => "保奈美",
		"first_name_ruby" => "ほなみ",
		"gender" => 2,
		"id" => 158,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "西川保奈美",
		"name_ruby" => "にしかわほなみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-03-12",
		"birth_day" => 17,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "西島",
		"family_name_ruby" => "にしじま",
		"first_name" => "櫂",
		"first_name_ruby" => "かい",
		"gender" => 2,
		"id" => 253,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "西島櫂",
		"name_ruby" => "にしじまかい",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-05-14",
		"birth_day" => 27,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "洲崎綾",
		"family_name" => "新田",
		"family_name_ruby" => "にった",
		"first_name" => "美波",
		"first_name_ruby" => "みなみ",
		"gender" => 2,
		"id" => 178,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "新田美波",
		"name_ruby" => "にったみなみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-12-19",
		"birth_day" => 3,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "二宮",
		"family_name_ruby" => "にのみや",
		"first_name" => "飛鳥",
		"first_name_ruby" => "あすか",
		"gender" => 2,
		"id" => 268,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "二宮飛鳥",
		"name_ruby" => "にのみやあすか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-11-06",
		"birth_day" => 4,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "丹羽",
		"family_name_ruby" => "にわ",
		"first_name" => "仁美",
		"first_name_ruby" => "ひとみ",
		"gender" => 2,
		"id" => 210,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "丹羽仁美",
		"name_ruby" => "にわひとみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 3,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "野々村",
		"family_name_ruby" => "ののむら",
		"first_name" => "そら",
		"first_name_ruby" => "そら",
		"gender" => 2,
		"id" => 110,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "野々村そら",
		"name_ruby" => "ののむらそら",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-28",
		"birth_day" => 11,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "服部",
		"family_name_ruby" => "はっとり",
		"first_name" => "瞳子",
		"first_name_ruby" => "とうこ",
		"gender" => 2,
		"id" => 135,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "服部瞳子",
		"name_ruby" => "はっとりとうこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 25,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "浜川",
		"family_name_ruby" => "はまかわ",
		"first_name" => "愛結奈",
		"first_name_ruby" => "あゆな",
		"gender" => 2,
		"id" => 111,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "浜川愛結奈",
		"name_ruby" => "はまかわあゆな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-04-13",
		"birth_day" => 13,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "浜口",
		"family_name_ruby" => "はまぐち",
		"first_name" => "あやめ",
		"first_name_ruby" => "あやめ",
		"gender" => 2,
		"id" => 175,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "浜口あやめ",
		"name_ruby" => "はまぐちあやめ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-03-12",
		"birth_day" => 9,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "早坂",
		"family_name_ruby" => "はやさか",
		"first_name" => "美玲",
		"first_name_ruby" => "みれい",
		"gender" => 2,
		"id" => 255,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "早坂美玲",
		"name_ruby" => "はやさかみれい",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-08-07",
		"birth_day" => 1,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "飯田友子",
		"family_name" => "速水",
		"family_name_ruby" => "はやみ",
		"first_name" => "奏",
		"first_name_ruby" => "かなで",
		"gender" => 2,
		"id" => 186,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "速水奏",
		"name_ruby" => "はやみかなで",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 14,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "原田",
		"family_name_ruby" => "はらだ",
		"first_name" => "美世",
		"first_name_ruby" => "みよ",
		"gender" => 2,
		"id" => 65,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "原田美世",
		"name_ruby" => "はらだみよ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 25,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "柊",
		"family_name_ruby" => "ひいらぎ",
		"first_name" => "志乃",
		"first_name_ruby" => "しの",
		"gender" => 2,
		"id" => 87,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "柊志乃",
		"name_ruby" => "ひいらぎしの",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 4,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "赤﨑千夏",
		"family_name" => "日野",
		"family_name_ruby" => "ひの",
		"first_name" => "茜",
		"first_name_ruby" => "あかね",
		"gender" => 2,
		"id" => 116,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "日野茜",
		"name_ruby" => "ひのあかね",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 14,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "杜野まこ",
		"family_name" => "姫川",
		"family_name_ruby" => "ひめかわ",
		"first_name" => "友紀",
		"first_name_ruby" => "ゆき",
		"gender" => 2,
		"id" => 108,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "姫川友紀",
		"name_ruby" => "ひめかわゆき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 3,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "兵藤",
		"family_name_ruby" => "ひょうどう",
		"first_name" => "レナ",
		"first_name_ruby" => "れな",
		"gender" => 2,
		"id" => 62,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "兵藤レナ",
		"name_ruby" => "ひょうどうれな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 21,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "福山",
		"family_name_ruby" => "ふくやま",
		"first_name" => "舞",
		"first_name_ruby" => "まい",
		"gender" => 2,
		"id" => 39,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "福山舞",
		"name_ruby" => "ふくやままい",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-03-01",
		"birth_day" => 1,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "藤居",
		"family_name_ruby" => "ふじい",
		"first_name" => "朋",
		"first_name_ruby" => "とも",
		"gender" => 2,
		"id" => 167,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "藤居朋",
		"name_ruby" => "ふじいとも",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-03-12",
		"birth_day" => 14,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "藤本",
		"family_name_ruby" => "ふじもと",
		"first_name" => "里奈",
		"first_name_ruby" => "りな",
		"gender" => 2,
		"id" => 254,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "藤本里奈",
		"name_ruby" => "ふじもとりな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-03-15",
		"birth_day" => 15,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "藤原",
		"family_name_ruby" => "ふじわら",
		"first_name" => "肇",
		"first_name_ruby" => "はじめ",
		"gender" => 2,
		"id" => 169,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "藤原肇",
		"name_ruby" => "ふじわらはじめ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 2,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "五十嵐裕美",
		"family_name" => "双葉",
		"family_name_ruby" => "ふたば",
		"first_name" => "杏",
		"first_name_ruby" => "あんず",
		"gender" => 2,
		"id" => 57,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "双葉杏",
		"name_ruby" => "ふたばあんず",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 18,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "古澤",
		"family_name_ruby" => "ふるさわ",
		"first_name" => "頼子",
		"first_name_ruby" => "よりこ",
		"gender" => 2,
		"id" => 94,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "古澤頼子",
		"name_ruby" => "ふるさわよりこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 4,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "",
		"family_name_ruby" => "",
		"first_name" => "ヘレン",
		"first_name_ruby" => "へれん",
		"gender" => 2,
		"id" => 80,
		"is_foreigner_name" => true,
		"is_idol" => true,
		"name" => "ヘレン",
		"name_ruby" => "へれん",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 10,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "",
		"family_name_ruby" => "",
		"first_name" => "ベテラントレーナー",
		"first_name_ruby" => "べてらんとれーなー",
		"gender" => 2,
		"id" => 125,
		"is_foreigner_name" => true,
		"is_idol" => false,
		"name" => "ベテラントレーナー",
		"name_ruby" => "べてらんとれーなー",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 5,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "渕上舞",
		"family_name" => "北条",
		"family_name_ruby" => "ほうじょう",
		"first_name" => "加蓮",
		"first_name_ruby" => "かれん",
		"gender" => 2,
		"id" => 88,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "北条加蓮",
		"name_ruby" => "ほうじょうかれん",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-09-18",
		"birth_day" => 6,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "松田颯水",
		"family_name" => "星",
		"family_name_ruby" => "ほし",
		"first_name" => "輝子",
		"first_name_ruby" => "しょうこ",
		"gender" => 2,
		"id" => 191,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "星輝子",
		"name_ruby" => "ほししょうこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-01-18",
		"birth_day" => 13,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "鈴木絵理",
		"family_name" => "堀",
		"family_name_ruby" => "ほり",
		"first_name" => "裕子",
		"first_name_ruby" => "ゆうこ",
		"gender" => 2,
		"id" => 212,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "堀裕子",
		"name_ruby" => "ほりゆうこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 1,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "原紗友里",
		"family_name" => "本田",
		"family_name_ruby" => "ほんだ",
		"first_name" => "未央",
		"first_name_ruby" => "みお",
		"gender" => 2,
		"id" => 95,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "本田未央",
		"name_ruby" => "ほんだみお",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 22,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "高森奈津美",
		"family_name" => "前川",
		"family_name_ruby" => "まえかわ",
		"first_name" => "みく",
		"first_name_ruby" => "みく",
		"gender" => 2,
		"id" => 50,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "前川みく",
		"name_ruby" => "まえかわみく",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 27,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "槙原",
		"family_name_ruby" => "まきはら",
		"first_name" => "志保",
		"first_name_ruby" => "しほ",
		"gender" => 2,
		"id" => 121,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "槙原志保",
		"name_ruby" => "まきはらしほ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 10,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "",
		"family_name_ruby" => "",
		"first_name" => "マスタートレーナー",
		"first_name_ruby" => "ますたーとれーなー",
		"gender" => 2,
		"id" => 126,
		"is_foreigner_name" => true,
		"is_idol" => false,
		"name" => "マスタートレーナー",
		"name_ruby" => "ますたーとれーなー",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-09-18",
		"birth_day" => 21,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "松尾",
		"family_name_ruby" => "まつお",
		"first_name" => "千鶴",
		"first_name_ruby" => "ちづる",
		"gender" => 2,
		"id" => 192,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "松尾千鶴",
		"name_ruby" => "まつおちづる",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 1,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "松永",
		"family_name_ruby" => "まつなが",
		"first_name" => "涼",
		"first_name_ruby" => "りょう",
		"gender" => 2,
		"id" => 81,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "松永涼",
		"name_ruby" => "まつながりょう",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 28,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "松原",
		"family_name_ruby" => "まつばら",
		"first_name" => "早耶",
		"first_name_ruby" => "さや",
		"gender" => 2,
		"id" => 52,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "松原早耶",
		"name_ruby" => "まつばらさや",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 1,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "松本",
		"family_name_ruby" => "まつもと",
		"first_name" => "沙理奈",
		"first_name_ruby" => "さりな",
		"gender" => 2,
		"id" => 68,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "松本沙理奈",
		"name_ruby" => "まつもとさりな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 21,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "松山",
		"family_name_ruby" => "まつやま",
		"first_name" => "久美子",
		"first_name_ruby" => "くみこ",
		"gender" => 2,
		"id" => 100,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "松山久美子",
		"name_ruby" => "まつやまくみこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-09-11",
		"birth_day" => 19,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "的場",
		"family_name_ruby" => "まとば",
		"first_name" => "梨沙",
		"first_name_ruby" => "りさ",
		"gender" => 2,
		"id" => 264,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "的場梨沙",
		"name_ruby" => "まとばりさ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 6,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "間中",
		"family_name_ruby" => "まなか",
		"first_name" => "美里",
		"first_name_ruby" => "みさと",
		"gender" => 2,
		"id" => 45,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "間中美里",
		"name_ruby" => "まなかみさと",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 29,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "真鍋",
		"family_name_ruby" => "まなべ",
		"first_name" => "いつき",
		"first_name_ruby" => "いつき",
		"gender" => 2,
		"id" => 106,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "真鍋いつき",
		"name_ruby" => "まなべいつき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 27,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "水木",
		"family_name_ruby" => "みずき",
		"first_name" => "聖來",
		"first_name_ruby" => "せいら",
		"gender" => 2,
		"id" => 78,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "水木聖來",
		"name_ruby" => "みずきせいら",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-06-26",
		"birth_day" => 5,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "水野",
		"family_name_ruby" => "みずの",
		"first_name" => "翠",
		"first_name_ruby" => "みどり",
		"gender" => 2,
		"id" => 182,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "水野翠",
		"name_ruby" => "みずのみどり",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 18,
		"birth_month" => 10,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "水本",
		"family_name_ruby" => "みずもと",
		"first_name" => "ゆかり",
		"first_name_ruby" => "ゆかり",
		"gender" => 2,
		"id" => 38,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "水本ゆかり",
		"name_ruby" => "みずもとゆかり",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-09",
		"birth_day" => 25,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "三船",
		"family_name_ruby" => "みふね",
		"first_name" => "美優",
		"first_name_ruby" => "みゆ",
		"gender" => 2,
		"id" => 129,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "三船美優",
		"name_ruby" => "みふねみゆ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 6,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "大坪由佳",
		"family_name" => "三村",
		"family_name_ruby" => "みむら",
		"first_name" => "かな子",
		"first_name_ruby" => "かなこ",
		"gender" => 2,
		"id" => 43,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "三村かな子",
		"name_ruby" => "みむらかなこ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 14,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "髙野麻美",
		"family_name" => "宮本",
		"family_name_ruby" => "みやもと",
		"first_name" => "フレデリカ",
		"first_name_ruby" => "ふれでりか",
		"gender" => 2,
		"id" => 54,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "宮本フレデリカ",
		"name_ruby" => "みやもとふれでりか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-02-29",
		"birth_day" => 25,
		"birth_month" => 6,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "三好",
		"family_name_ruby" => "みよし",
		"first_name" => "紗南",
		"first_name_ruby" => "さな",
		"gender" => 2,
		"id" => 165,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "三好紗南",
		"name_ruby" => "みよしさな",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 7,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "向井",
		"family_name_ruby" => "むかい",
		"first_name" => "拓海",
		"first_name_ruby" => "たくみ",
		"gender" => 2,
		"id" => 122,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "向井拓海",
		"name_ruby" => "むかいたくみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-01-18",
		"birth_day" => 1,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "棟方",
		"family_name_ruby" => "むなかた",
		"first_name" => "愛海",
		"first_name_ruby" => "あつみ",
		"gender" => 2,
		"id" => 213,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "棟方愛海",
		"name_ruby" => "むなかたあつみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-06-26",
		"birth_day" => 3,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "村上",
		"family_name_ruby" => "むらかみ",
		"first_name" => "巴",
		"first_name_ruby" => "ともえ",
		"gender" => 2,
		"id" => 184,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "村上巴",
		"name_ruby" => "むらかみともえ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-08-14",
		"birth_day" => 27,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "村松",
		"family_name_ruby" => "むらまつ",
		"first_name" => "さくら",
		"first_name_ruby" => "さくら",
		"gender" => 2,
		"id" => 187,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "村松さくら",
		"name_ruby" => "むらまつさくら",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-01-31",
		"birth_day" => 19,
		"birth_month" => 1,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "コクラン",
		"family_name_ruby" => "こくらん",
		"first_name" => "メアリー",
		"first_name_ruby" => "めありー",
		"gender" => 2,
		"id" => 159,
		"is_foreigner_name" => true,
		"is_idol" => true,
		"name" => "メアリー・コクラン",
		"name_ruby" => "めありーこくらん",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 24,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "持田",
		"family_name_ruby" => "もちだ",
		"first_name" => "亜里沙",
		"first_name_ruby" => "ありさ",
		"gender" => 2,
		"id" => 42,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "持田亜里沙",
		"name_ruby" => "もちだありさ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-09",
		"birth_day" => 25,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "望月",
		"family_name_ruby" => "もちづき",
		"first_name" => "聖",
		"first_name_ruby" => "ひじり",
		"gender" => 2,
		"id" => 132,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "望月聖",
		"name_ruby" => "もちづきひじり",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 7,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "桃井",
		"family_name_ruby" => "ももい",
		"first_name" => "あずき",
		"first_name_ruby" => "あずき",
		"gender" => 2,
		"id" => 59,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "桃井あずき",
		"name_ruby" => "ももいあずき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-11-06",
		"birth_day" => 27,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "森久保",
		"family_name_ruby" => "もりくぼ",
		"first_name" => "乃々",
		"first_name_ruby" => "のの",
		"gender" => 2,
		"id" => 211,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "森久保乃々",
		"name_ruby" => "もりくぼのの",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 1,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "松嵜麗",
		"family_name" => "諸星",
		"family_name_ruby" => "もろぼし",
		"first_name" => "きらり",
		"first_name_ruby" => "きらり",
		"gender" => 2,
		"id" => 117,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "諸星きらり",
		"name_ruby" => "もろぼしきらり",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 29,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "楊",
		"family_name_ruby" => "やお",
		"first_name" => "菲菲",
		"first_name_ruby" => "ふぇいふぇい",
		"gender" => 2,
		"id" => 58,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "楊菲菲",
		"name_ruby" => "やおふぇいふぇい",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-07-17",
		"birth_day" => 7,
		"birth_month" => 11,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "八神",
		"family_name_ruby" => "やがみ",
		"first_name" => "マキノ",
		"first_name_ruby" => "まきの",
		"gender" => 2,
		"id" => 261,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "八神マキノ",
		"name_ruby" => "やがみまきの",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 10,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "矢口",
		"family_name_ruby" => "やぐち",
		"first_name" => "美羽",
		"first_name_ruby" => "みう",
		"gender" => 2,
		"id" => 103,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "矢口美羽",
		"name_ruby" => "やぐちみう",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 12,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "柳",
		"family_name_ruby" => "やなぎ",
		"first_name" => "清良",
		"first_name_ruby" => "きよら",
		"gender" => 2,
		"id" => 64,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "柳清良",
		"name_ruby" => "やなぎきよら",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 16,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "柳瀬",
		"family_name_ruby" => "やなせ",
		"first_name" => "美由紀",
		"first_name_ruby" => "みゆき",
		"gender" => 2,
		"id" => 49,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "柳瀬美由紀",
		"name_ruby" => "やなせみゆき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-03-12",
		"birth_day" => 16,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "大和",
		"family_name_ruby" => "やまと",
		"first_name" => "亜季",
		"first_name_ruby" => "あき",
		"gender" => 2,
		"id" => 256,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "大和亜季",
		"name_ruby" => "やまとあき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-05-21",
		"birth_day" => 17,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "結城",
		"family_name_ruby" => "ゆうき",
		"first_name" => "晴",
		"first_name_ruby" => "はる",
		"gender" => 2,
		"id" => 259,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "結城晴",
		"name_ruby" => "ゆうきはる",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-07-17",
		"birth_day" => 19,
		"birth_month" => 2,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "遊佐",
		"family_name_ruby" => "ゆさ",
		"first_name" => "こずえ",
		"first_name_ruby" => "こずえ",
		"gender" => 2,
		"id" => 260,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "遊佐こずえ",
		"name_ruby" => "ゆさこずえ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-03-15",
		"birth_day" => 18,
		"birth_month" => 12,
		"character_type" => 4,
		"class_name" => "cute",
		"cv" => "",
		"family_name" => "横山",
		"family_name_ruby" => "よこやま",
		"first_name" => "千佳",
		"first_name_ruby" => "ちか",
		"gender" => 2,
		"id" => 168,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "横山千佳",
		"name_ruby" => "よこやまちか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-31",
		"birth_day" => 8,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "吉岡",
		"family_name_ruby" => "よしおか",
		"first_name" => "沙紀",
		"first_name_ruby" => "さき",
		"gender" => 2,
		"id" => 143,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "吉岡沙紀",
		"name_ruby" => "よしおかさき",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2014-05-28",
		"birth_day" => 3,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "依田",
		"family_name_ruby" => "よりた",
		"first_name" => "芳乃",
		"first_name_ruby" => "よしの",
		"gender" => 2,
		"id" => 275,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "依田芳乃",
		"name_ruby" => "よりたよしの",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2013-09-11",
		"birth_day" => 21,
		"birth_month" => 5,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "",
		"family_name_ruby" => "",
		"first_name" => "ライラ",
		"first_name_ruby" => "らいら",
		"gender" => 2,
		"id" => 263,
		"is_foreigner_name" => true,
		"is_idol" => true,
		"name" => "ライラ",
		"name_ruby" => "らいら",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 20,
		"birth_month" => 7,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "龍崎",
		"family_name_ruby" => "りゅうざき",
		"first_name" => "薫",
		"first_name_ruby" => "かおる",
		"gender" => 2,
		"id" => 98,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "龍崎薫",
		"name_ruby" => "りゅうざきかおる",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-04-26",
		"birth_day" => 10,
		"birth_month" => 3,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "",
		"family_name_ruby" => "",
		"first_name" => "ルーキートレーナー",
		"first_name_ruby" => "るーきーとれーなー",
		"gender" => 2,
		"id" => 177,
		"is_foreigner_name" => true,
		"is_idol" => false,
		"name" => "ルーキートレーナー",
		"name_ruby" => "るーきーとれーなー",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-11-28",
		"birth_day" => 30,
		"birth_month" => 8,
		"character_type" => 4,
		"class_name" => "passion",
		"cv" => "",
		"family_name" => "若林",
		"family_name_ruby" => "わかばやし",
		"first_name" => "智香",
		"first_name_ruby" => "ともか",
		"gender" => 2,
		"id" => 112,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "若林智香",
		"name_ruby" => "わかばやしともか",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2012-04-17",
		"birth_day" => 20,
		"birth_month" => 9,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "脇山",
		"family_name_ruby" => "わきやま",
		"first_name" => "珠美",
		"first_name_ruby" => "たまみ",
		"gender" => 2,
		"id" => 176,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "脇山珠美",
		"name_ruby" => "わきやまたまみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	},
	{
		"arrival_date" => "2011-12-31",
		"birth_day" => 7,
		"birth_month" => 4,
		"character_type" => 4,
		"class_name" => "cool",
		"cv" => "",
		"family_name" => "和久井",
		"family_name_ruby" => "わくい",
		"first_name" => "留美",
		"first_name_ruby" => "るみ",
		"gender" => 2,
		"id" => 142,
		"is_foreigner_name" => false,
		"is_idol" => true,
		"name" => "和久井留美",
		"name_ruby" => "わくいるみ",
		"origin_media" => "アイドルマスター シンデレラガールズ"
	}
]


	def to_fullname(name)
		name = Romaji.romaji2kana name, :kana_type => :hiragana if name =~ /\w/
		name_r = /#{name}/
		
		result = CHARACTER_LIST.select { |chara|
			chara["name_ruby"] =~ name_r
		}.map { |it| it["name"] }
		result.empty? ? [name] : result
	end


	def rarity_to_n(rarity)
		case rarity
		when 'N'
			1
		when 'N+'
			2
		when 'R'
			3
		when 'R+'
			4
		when 'SR'
			5
		when 'SR+'
			6
		else
			1
		end
	end

	def search(query)
		response = Net::HTTP.get "ppdb.sekai.in", "/api/2/idol.json?full=1&name=#{ERB::Util.url_encode query[:name]}"
		result = JSON.parse(response)
		if result["result"] == false
			return nil
		end

		idols = result["data"]
		if query[:regexp]
			regexp = /#{NKF.nkf("-w -x -Z4", Romaji.romaji2kana(query[:regexp].source))}/i
			idols.select! { |it| it["Name"] =~ regexp }
		end
		if query[:rarity] == nil
			return idols
		end

		rarity = rarity_to_n query[:rarity]
		idols.select! { |idol|
			idol["Rarity"] == rarity
		}
	end


	def to_image_url(id, frame = true)
		if frame
			"http://125.6.169.35/idolmaster/image_sp/card/l/#{ id }.jpg"
		else
			"http://125.6.169.35/idolmaster/image_sp/card/l_noframe/#{ id }.jpg"
		end
	end


	def search_random(query)
		result = search(query)
		if !result
			return nil
		end
		result[rand(result.length)]
	end

	def search_random_img(query)
		idol = search_random query
		if idol.nil?
			return nil
		end
		to_mobamasu_image_url(idol["ID"], query[:frame])
	end

	def parse_request(request, prefix = "#mobamasul?!?")
		if request !~ /#{prefix}[\s　].*/
			return nil
		end
		(op, search_word, *args) = request.split(/[\s　]+/, 4)
		if search_word.nil?
			return nil
		end

		rarity = nil
		regexp = nil
		args.each do |arg|
			if arg =~ /^(N|N\+|R|R\+|SR|SR\+)(,(N|N\+|R|R\+|SR|SR\+))*$/
				rarity = arg
			end
			if arg =~ /^\/.*\/$/
				regexp = Regexp.new(NKF::nkf('-WwXm0', arg[1..-2]))
			end
		end
		frame = true
		if op =~ /#mobamasu!/
			frame = false
		end

		search_word = Romaji.romaji2kana search_word, :kana_type => :hiragana if search_word =~ /\w/
		{ :name => search_word, :rarity => rarity, :frame => frame, :regexp => regexp }
	end


	def search_loading(query)
		names = Mobamasu.to_fullname(query[:name]).map { |it| NKF.nkf("-w -x -Z4", it) }

		url = "http://imcgcollector.blog.fc2.com/blog-entry-994.html"

		agent = Mechanize.new
		page = agent.get(url)
		tables = (page/:table)[5, 17]

		chars = tables.search(:tr).select { |tr|
			td = tr/:td
			   (td[0] && names.find { |it| td[0].inner_text =~ /#{it}/ } && td[2][:bgcolor] != "#cccccc")	\
			|| (td[1] && names.find { |it| td[1].inner_text =~ /#{it}/ } && td[3][:bgcolor] != "#cccccc")
		}

		chars.map! { |it|
			name = (it/:td)[0].inner_text
			name = (it/:td)[1].inner_text if name =~ /^[★◆]$/
			{
				:name => name.gsub(/.?[\(（]\d*[\)）].?/, ""),
				:katagaki  => (it/:a)[1][:href],
				:loading_icon  => (it/:a)[2][:href]
			}
		}
		if query[:regexp]
			regexp = /#{NKF.nkf("-w -x -Z4", Romaji.romaji2kana(query[:regexp].source))}/
			chars.select { |it| it[:name] =~ regexp }
		else
			chars
		end
	end

	def search_music query
		query = /#{to_fullname(query).first}/
		term = "IDOLM@STER CINDERELLA"
		response = Net::HTTP.get "ax.itunes.apple.com", "/WebObjects/MZStoreServices.woa/wa/wsSearch?term=#{ERB::Util.url_encode term}&country=JP&entity=musicTrack"
		JSON.parse(response)["results"].select { |it| it["artistName"] =~ query || it["trackName"] =~ query }
	end

	module_function :parse_request
	module_function :rarity_to_n
	module_function :search
	module_function :search_random
	module_function :to_image_url
	module_function :search_loading
	module_function :to_fullname
	module_function :search_music



	def search_kumajet_by_matome_page url, query
		page = Mechanize.new.get(url)
		titles = page.at(".ently_text").text[/^.*\n(.*)\n/, 1].scan(/第\d+話【.+?】/)
		title = titles.find { |it| it =~ /#{query}/ }
		if title.nil?
			return
		end
		number = title[/^第(\d+)話/, 1]
		{
			title: title,
			image: page.link_with(:href => /c\/g\/g\/cggekijo\/#{number}\.jpg/).href
		}
	end


	def search_kumajet_by_backnumber query
		if query !~ /(\d+)|%(第?(\d+)話)/
			return
		end
		backnumber = $1
		backnumberp = /第#{(backnumber.to_i - 1) / 10 * 10 + 1}/
		page = Mechanize.new.get("http://cggekijo.blog.fc2.com/")
		result = (page.search(".plugin2_outline")[1]/:a).find { |it| it.inner_text =~ backnumberp }
		if result
			search_kumajet_by_matome_page result[:href], backnumber
		end
	end


	def search_kumajet_by_title query
		url = "http://cggekijo.blog.fc2.com/?q=#{ERB::Util.url_encode query}"
		agent = Mechanize.new
		page = agent.get(url)

		queryp = /#{query}/
		entlys = page.search(".ently_outline")
		if entlys.empty?
			return
		end

		result = entlys.find { |it| it.at(".ently_title").inner_text =~ queryp }
		if result
			ently = result
			return {
				title: ently.at(".ently_title").inner_text[/シンデレラガールズ劇場\s+(.*)/, 1],
				image: ently.at(:img)[:src]
			}
		end
		
		result = entlys.find { |it| it.at(".ently_title").inner_text =~ /まとめ/ }
		if result
			return search_kumajet_by_matome_page result.at(:a)[:href], query
		end
	end

	def search_kumajet query
		if query =~ /(\d+)|%(第?(\d+)話)/
			search_kumajet_by_backnumber query
		else
			search_kumajet_by_title query
		end
	end

	module_function :search_kumajet, :search_kumajet_by_title, :search_kumajet_by_backnumber, :search_kumajet_by_matome_page


	def search_yougo query
		url = "http://www18.atwiki.jp/imas_cg/pages/119.html"
		page = Mechanize.new.get(url)
		index = (page.at(".plugin_contents")/:a)
		result = index.find { |it| it.inner_text == query }
		if result.nil?
			result = index.find { |it| it.inner_text =~ /#{query}/ }
			if result.nil?
				return
			end
		end
		id = result[:href][/#(id_\w+)/, 1]
		{
			title: result.inner_text,
			body: page.at("##{id} + div").inner_text,
			link: result[:href]
		}
	end

	module_function :search_yougo

end



